[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
manna_controller = "7QZLtciaBCeLy5uyooZERzBNbPLNuQ6Ppc4iA2kqEsyR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/manna-worldstreet/fee-payer-devnet.json"

[workspace]
members = ["programs/manna-controller"]

[scripts]
test = "anchor test"
